const fs = require("fs");
const path = require("path");

const SCHEMA_PATH =
  process.env.SCHEMA_PATH ||
  path.resolve(__dirname, "../../schema.config.json");
const PRISMA_OUTPUT = path.resolve(__dirname, "../../prisma/schema.prisma");

function fieldTypeToPrisma(field) {
  const mapping = {
    string: "String",
    text: "String",
    number: "Float",
    boolean: "Boolean",
    date: "DateTime",
    enum: "String",
  };
  return mapping[field.type] || "String";
}

function generatePrismaSchema(config) {
  let schema = `// Auto-generated by dash-drop — do not edit manually
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
`;

  for (const entity of config.entities) {
    const modelName = entity.name;
    schema += `\nmodel ${modelName} {\n`;
    schema += `  id        Int      @id @default(autoincrement())\n`;

    for (const field of entity.fields) {
      if (field.type === "list") continue; // skip relations for MVP

      const prismaType = fieldTypeToPrisma(field);
      const optional = field.required ? "" : "?";
      let defaultVal = "";

      if (field.default !== undefined) {
        if (typeof field.default === "boolean") {
          defaultVal = ` @default(${field.default})`;
        } else if (typeof field.default === "number") {
          defaultVal = ` @default(${field.default})`;
        } else {
          defaultVal = ` @default("${field.default}")`;
        }
      }

      schema += `  ${field.name.padEnd(12)} ${prismaType}${optional}${defaultVal}\n`;
    }

    schema += `  createdAt   DateTime @default(now())\n`;
    schema += `  updatedAt   DateTime @updatedAt\n`;
    schema += `}\n`;
  }

  return schema;
}

function main() {
  const raw = fs.readFileSync(SCHEMA_PATH, "utf-8");
  const config = JSON.parse(raw);
  const prismaSchema = generatePrismaSchema(config);

  fs.mkdirSync(path.dirname(PRISMA_OUTPUT), { recursive: true });
  fs.writeFileSync(PRISMA_OUTPUT, prismaSchema);
  console.log(`Prisma schema written to ${PRISMA_OUTPUT}`);
}

main();

module.exports = { generatePrismaSchema };
